### ISSUE TITLE
Generating large (repeatable) files for archival-tool testing

### ISSUE THREAD

**Issue by Joshfindit** [Tronic/fastrandom#3]
This repo ticks a lot of my “is this compelling?” boxes. Fast, tested, results shared, simple.

I’m looking for something to generate arbitrarily-large files for testing backup/recovery tools and wonder if I can use this as-is, or whether you’re open to adding some flags to the interface.

Needed features:

- Specify the size of the output file in B/MB/GB/TB/etc
- Specify the “seed” so that for each specific (small) input, the same large file will be created

Use-case is adding this to a CD/CI flow where the tests are committed to the git repo and the files are generated during test runs.

**Comment by Tronic** [comment]
Thanks, good if you find use for this.

By the means that this works, namely that of running many threads that each write out randomness as fast as they can, it is not possible to produce repeatable streams. You would need a single-threaded tool (limited to about 1 GB/s) or some sort of synchronization among the workers, neither of which are planned for this tool.

For similar reasons, this tool does not have an option to produce output of some exact size. Adding an option to produce roughly some size would be easy and it wouldn't be entirely impossible to implement a strict total amount either (at a negligible performance loss for synchronization). PRs are welcome!

**Comment by Joshfindit** [comment]
Hmmm.

Since the content of the file doesn’t matter (only that it’s “random” and repeatable), would it work to split the job in to threads, then concatenate the resulting output? Or is exploring that approach more trouble than it’s worth?

**Comment by Tronic** [comment]
You would want one chunk from each worker thread, in sequential order, then the output can be deterministic. For that you'd have to rewrite much of this tool and if you still want to keep it maximally fast, the logic needs to be more complicated (generating the next block while waiting to write out the previous one). I don't see this being implemented in this tool, but if you are interested and can make a sensible solution, PRs are welcome on that too.

**Comment by Joshfindit** [comment]
I won’t try to shoehorn my use-case in to this tool (though I do feel like it’s convinced me to build a tool that uses encryption).

Thank you. I appreciate your taking the time to respond.
